geo_id,type,coordinates,resource_id,resource_type
0,Point,[],num00_rotaryPipeAutomaticWeldingMachine_ws0,machine
1,Point,[],num00_rotaryPipeAutomaticWeldingMachine_ws1,machine
2,Point,[],num01_weldingRobot_ws0,machine
3,Point,[],num02_rollerbedCNCPipeIntersectionCuttingMachine_ws0,machine
4,Point,[],num04_groovingMachineLarge_ws0,machine
5,Point,[],num08_workbench_ws0,machine
6,Point,[],num08_workbench_ws1,machine
7,Point,[],gantry_0,gantry
8,Point,[],gantry_1,gantry
9,Point,[],human_0,human
10,Point,[],human_1,human
11,Point,[],human_2,human
12,Point,[],human_3,human
13,Point,[],human_4,human
14,Point,[],robot_0,transport_robot
15,Point,[],robot_1,transport_robot
16,Point,[],storage_BlackStorage_00,buffer
17,Point,[],storage_BlackStorage_01,buffer
18,Point,[],storage_BlackStorage_02,buffer
19,Point,[],storage_BlackStorage_03,buffer
20,Point,[],storage_BlackStorage_04,buffer
21,Point,[],storage_GroundStorage_00,buffer
22,Point,[],storage_GroundStorage_01,buffer
23,Point,[],storage_YellowStorage_00,buffer
24,Point,[],storage_YellowStorage_01,buffer
25,Point,[],storage_YellowStorage_02,buffer
26,Point,[],storage_YellowStorage_03,buffer
27,Point,[],storage_YellowStorage_04,buffer
28,Point,[],storage_YellowStorage_05,buffer
29,Point,[],storage_YellowStorage_06,buffer
30,Point,[],storage_YellowStorage_07,buffer
31,Point,[],storage_YellowStorage_08,buffer
32,Point,[],storage_YellowStorage_09,buffer
33,Point,[],storage_YellowStorage_10,buffer
